### ISSUE TITLE
Maven Dependency and small version problem with spring-redis-integration

### ISSUE THREAD

**Issue by chafka** [spring-cloud/spring-cloud-cluster#12]
Hi Alain, 
I am happy that I found this source code on your github profile. I tested and it is doing perfect. I had a one issue and that was about my spring-redis-integration version. This code works very good with spring-redis-integration 4.1.4-RELEASE but it doesn't go through the second test on 4.1.6-RELEASE.
And if possible, could you please include a maven dependency so we can easily get this superb code. 
Keep up the good work!

**Comment by dsyer** [comment]
Who is Alain? Anyway, can you explain a bit what you did and what didn't work?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
