### ISSUE TITLE
Split Out Boot Dependencies

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-cluster#16]
As discussed in slack, we need to split out the boot dependencies (configuration) into a separate project.

Currently, we can't depend on this project in Spring Integration because we'll end up with a circular dependency `si->sccc->boot->si`.

For now, I have copied the core components (`Context`, `Candidate`, events, `LeaderInitiator`) to SI so we can get a milestone out, but it would be preferable to have this refactoring done for the SI RC (mid-August).

**Comment by dsyer** [comment]
Maybe SI is the right place for those abstractions anyway then? It's a bit of a fuzzy line.

**Comment by garyrussell** [comment]
Works for me if it's ok for s-c-c-core to depend on SI-core and  s-c-c-zookeeper to depend on SI-zookeeper.

BTW, that will just leave `ZookeeperClusterProperties` (`@ConfigurationProperties`) in s-c-c-z.

Also see @spencergibb 's comment in [this PR](https://github.com/spring-cloud/spring-cloud-cluster/pull/15) which adds `SmartLifecycle` to the curator client.

/cc @pperalta
