### ISSUE TITLE
Create a new module for global locks and add redis implementation

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-cluster#2]

**Comment by jvalkeal** [comment]
I'm planning to try this out and do some prototyping.

**Comment by jvalkeal** [comment]
google led me to something I didn't know even exist, namely http://docs.spring.io/spring-integration/api/org/springframework/integration/support/locks/LockRegistry.html and http://docs.spring.io/spring-integration/api/org/springframework/integration/redis/util/RedisLockRegistry.html.

Paging @dsyer @garyrussell. I think we need to decide if we could use deps from SI or copy stuff over to cloud modules or at least re-use some of that code.

**Comment by garyrussell** [comment]
Also see https://jira.spring.io/browse/INT-3616.

**Comment by jvalkeal** [comment]
Merged
