### ISSUE TITLE
Yielding leadership in Hazelcast

### ISSUE THREAD

**Issue by mixas27** [spring-cloud/spring-cloud-cluster#29]
Hello,

I have 2 nodes cluster managed by hazelcast v. 3.5.4 and spring-cloud-cluster-hazelcast v. 1.0.0.1.M1.
On first node I revoke leadership via JMX using ```DefaultCandidate.yieldLeadership() ``` method and after revoking leadership, if first node became leader again without restart, calling ```DefaultCandidate.yieldLeadership() ``` makes no effect. Node does not yield leadership more.

I analyzed sources and found what ```HazelcastContext#yield()``` method just cancels ```Future``` instance. And calling ```camcel()``` method on alredy canceled ```Future``` instance makes no effect.

In my oppinion,   you should break ```while``` loop in ```LeaderInitiator.Initiator``` when ```InterruptedException``` occurs and submit a new ```LeaderInitiator.Initiator``` instance to executorService in ```HazelcastContext#yield``` method.

I can create pull request if necessary. 
Thanks in advance

**Comment by mifmax** [comment]
Hi, 
I tried to replace the method HazelcastContext.yield() to

```
        @Override
        public void yield()
        {
            stop();
            try
            {
                Thread.sleep(100);
            }
            catch (InterruptedException e)
            {
                // Catch and log InterruptedException exceptions.
                // We must wait method Initiator.call() out of the loop
                logger.warn("Exception caught for sleep in yield", e);
            }
            start();
        }
```
And now the leadership can change more than once on each node. 
Please look @pperalta . It is very important to have the possibility several times to change leadership

P.S:
Maybe I'm not very nice changed the method and did not consider the details, this is just an example of the working method of leadership change.
