### ISSUE TITLE
further support to spring-cloud-cluster-hazelcast after deprecation

### ISSUE THREAD

**Issue by franciscospaeth** [spring-cloud/spring-cloud-cluster#30]
Is there any guide or hints on how to migrate from `spring-cloud-cluster-hazelcast` to `spring-integration`. I can't really find a way to integrate hazelcast LeaderInitiator implementation when using `spring-integration` in place of `spring-cloud-cluster`.

Checking integration repository (https://repo.spring.io/release/org/springframework/integration/) I couldn't find any integration to hazelcast.

**Comment by dsyer** [comment]
Hazelcast is an extension: https://github.com/spring-projects/spring-integration-extensions/tree/master/spring-integration-hazelcast. I'll update the README, thanks.
