### ISSUE TITLE
[Question] Cluster Consul

### ISSUE THREAD

**Issue by xenji** [spring-cloud/spring-cloud-cluster#31]
Hey folks, 

I'd like to ask if there is any intention to revive the consul branch and add consul to the supported technologies? 

BTW: I tried to integrate the branch in the state of the current master, but failed in doing so (due to some dependency errors that I cannot really get sorted).

Regards,
Mario

**Comment by spencergibb** [comment]
From the first line of the README:

> This project is now superseded by code in Spring Integration. All the interfaces here have counterparts in the main Spring libraries, and the implementations are mostly parallel too (etcd is an exception because of the lack of support for v3 in third party libraries). The 1.0.1 release deprecates everything in favour of Spring Integration.

Anything in this project is now deprecated. There would need to be code in spring-integration similar to this https://github.com/spring-projects/spring-integration/tree/master/spring-integration-zookeeper
