### ISSUE TITLE
Lack RedisLeaderAutoConfiguration

### ISSUE THREAD

**Issue by HuangDayu** [spring-cloud/spring-cloud-cluster#36]
Chinese：你好，由于缺少了RedisLeaderAutoConfiguration，导致不能使用spring-cloud-cluster-redis开启集群选举。以后还会完善吗？谢谢。  

English：Hello, due to the lack of `RedisLeaderAutoConfiguration`, `spring-cloud-cluster-redis` cannot be used to start cluster elections. Will it be improved in the future? Thanks.

**Comment by spencergibb** [comment]
This project has long been superseded by spring integration
